Feature/nfts act
codeLover1126/smart-app pull request #4
Opened 2023-06-08 08:43 UTC by AtlasSchmidt

2023-06-08 09:14 UTC, codeLover1126 requested changes
Nice job! Please make sure the indentation space is 2, not 4.

2023-06-08 09:14 UTC, codeLover1126 commented on src/components/Blog/index.js
> +
NEVER put a blank line at the beginning of the component.

2023-06-08 09:14 UTC, codeLover1126 commented on src/components/Blog/index.js
> +        console.log(res)
Please get rid of all `console`s.

2023-06-08 09:14 UTC, codeLover1126 commented on src/components/Blog/index.js
> +    const getBlog = async () => {
Indentation size is 2, not 4.

2023-06-08 09:14 UTC, codeLover1126 commented on src/components/Blog/index.js
> +    useEffect(() => {
It's good to add a blank line above here and after this `useEffect` declaration.

2023-06-08 09:14 UTC, codeLover1126 commented
Again, no description!

2023-06-08 09:33 UTC, AtlasSchmidt commented on src/components/Blog/index.js
> +
this is resolved

2023-06-08 09:33 UTC, AtlasSchmidt commented on src/components/Blog/index.js
> +        console.log(res)
this is resolved

2023-06-08 09:34 UTC, AtlasSchmidt commented on src/components/Blog/index.js
> +    const getBlog = async () => {
sorry, this is resolved

2023-06-08 09:35 UTC, AtlasSchmidt commented on src/components/Blog/index.js
> +    useEffect(() => {
this is resolved

2023-06-09 02:41 UTC, codeLover1126 commented
Please pull from `features/nfts-ui` and resolve conflict.

2023-06-10 08:25 UTC, merged